--- #YAML:1.0
name:               Attribute-Signature
version:            1.10
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    Attribute::Handlers:  0.7
    perl:                 5.006
    Scalar::Util:         0.01
resources:
    repository:        http://github.com/chorny/Attribute-Signature
    Repository-clone:  git://github.com/chorny/Attribute-Signature.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
